version: '3'
services:
  database:
    build:
      context: ./infraestructure/postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=stori-challenge-db
    networks: 
      - stori-challenge-network

  file-rest:
    build:
      context: .
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=stori-challenge-db
    ports:
      - '8080:8080'
    networks:
      - stori-challenge-network

networks:
  stori-challenge-network: